idle_bg = "{background}"
idle_fg = "{foreground}"
good_bg = "{background}"
good_fg = "{foreground}"
warning_bg = "{color3}"
warning_fg = "{color0}"
critical_bg = "#ffffff"
critical_fg = "#ff0000"
info_bg = "{color0}"
info_fg = "{color1}"
alternating_tint_bg = "{background}"
alternating_tint_fg = "{background}"
# separator_bg = "{color0}"
# separator_fg = "{color1}"
separator = "|"
end_separator = ""
start_separator = "<"
