[colors.primary]
background = "#000000"
foreground = "#dedede"

[colors.cursor]
text = "#000000"
cursor = "#dedede"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#dedede"

[colors.search.matches]
foreground = "#000000"
background = "#dedede"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#9b9b9b"
background = "#dedede"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#474747"
green = "#585858"
yellow = "#676767"
blue = "#777777"
magenta = "#8E8E8E"
cyan = "#AFAFAF"
white = "#dedede"

[colors.bright]
black = "#9b9b9b"
red = "#474747"
green = "#585858"
yellow = "#676767"
blue = "#777777"
magenta = "#8E8E8E"
cyan = "#AFAFAF"
white = "#dedede"

[colors.dim]
black = "#dedede"
red = "#474747"
green = "#8E8E8E"
yellow = "#676767"
blue = "#777777"
magenta = "#585858"
cyan = "#AFAFAF"
white = "#9b9b9b"
