[colors.primary]
background = "#09030d"
foreground = "#ddbfae"

[colors.cursor]
text = "#09030d"
cursor = "#ddbfae"

[colors.vi_mode_cursor]
text = "#09030d"
cursor = "#ddbfae"

[colors.search.matches]
foreground = "#09030d"
background = "#ddbfae"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#9a8579"
background = "#ddbfae"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#09030d"
red = "#682126"
green = "#6E5050"
yellow = "#615458"
blue = "#992227"
magenta = "#CB483F"
cyan = "#926055"
white = "#ddbfae"

[colors.bright]
black = "#9a8579"
red = "#682126"
green = "#6E5050"
yellow = "#615458"
blue = "#992227"
magenta = "#CB483F"
cyan = "#926055"
white = "#ddbfae"

[colors.dim]
black = "#ddbfae"
red = "#682126"
green = "#CB483F"
yellow = "#615458"
blue = "#992227"
magenta = "#6E5050"
cyan = "#926055"
white = "#9a8579"
