[colors.primary]
background = "#070710"
foreground = "#c1c1c3"

[colors.cursor]
text = "#070710"
cursor = "#c1c1c3"

[colors.vi_mode_cursor]
text = "#070710"
cursor = "#c1c1c3"

[colors.search.matches]
foreground = "#070710"
background = "#c1c1c3"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#565669"
background = "#c1c1c3"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#070710"
red = "#585FB1"
green = "#5573DE"
yellow = "#9172A0"
blue = "#3D81F9"
magenta = "#5A8AFB"
cyan = "#6998FE"
white = "#c1c1c3"

[colors.bright]
black = "#565669"
red = "#585FB1"
green = "#5573DE"
yellow = "#9172A0"
blue = "#3D81F9"
magenta = "#5A8AFB"
cyan = "#6998FE"
white = "#c1c1c3"

[colors.dim]
black = "#c1c1c3"
red = "#585FB1"
green = "#5A8AFB"
yellow = "#9172A0"
blue = "#3D81F9"
magenta = "#5573DE"
cyan = "#6998FE"
white = "#565669"
