idle_bg = "#15150a"
idle_fg = "#987553"
# idle_bg = "#15150a"
# idle_fg = "#dbd6c9"
good_bg = "#15150a"
good_fg = "#987553"
# good_bg = "#15150a"
# good_fg = "#dbd6c9"
# good_bg = "#CBAB3B"
# good_fg = "#15150a"
warning_bg = "#AD8E67"
warning_fg = "#15150a"
critical_bg = "#ffffff"
critical_fg = "#ff0000"
info_bg = "#15150a"
info_fg = "#987553"
# alternating_tint_bg = "#dbd6c9"
# alternating_tint_fg = "#15150a"
separator_bg = "#15150a"
separator_fg = "#15150a"
separator = "|"
end_separator = ""
start_separator = "<"
