idle_bg = "#09030d"
idle_fg = "#682126"
# idle_bg = "#09030d"
# idle_fg = "#ddbfae"
good_bg = "#09030d"
good_fg = "#682126"
# good_bg = "#09030d"
# good_fg = "#ddbfae"
# good_bg = "#6E5050"
# good_fg = "#09030d"
warning_bg = "#615458"
warning_fg = "#09030d"
critical_bg = "#ffffff"
critical_fg = "#ff0000"
info_bg = "#09030d"
info_fg = "#682126"
# alternating_tint_bg = "#ddbfae"
# alternating_tint_fg = "#09030d"
separator_bg = "#09030d"
separator_fg = "#09030d"
separator = "|"
end_separator = ""
start_separator = "<"
