idle_bg = "#070710"
idle_fg = "#585FB1"
# idle_bg = "#070710"
# idle_fg = "#c1c1c3"
good_bg = "#070710"
good_fg = "#585FB1"
# good_bg = "#070710"
# good_fg = "#c1c1c3"
# good_bg = "#5573DE"
# good_fg = "#070710"
warning_bg = "#9172A0"
warning_fg = "#070710"
critical_bg = "#ffffff"
critical_fg = "#ff0000"
info_bg = "#070710"
info_fg = "#585FB1"
# alternating_tint_bg = "#c1c1c3"
# alternating_tint_fg = "#070710"
separator_bg = "#070710"
separator_fg = "#070710"
separator = "|"
end_separator = ""
start_separator = "<"
